name: CI/CD

on:
  push:
    branches:
      - prod  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to EC2
        if: success() 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # Save private key to file
          echo "$SSH_PRIVATE_KEY" > private_key.pem

          # Secure the key
          chmod 600 private_key.pem  

          # SSH into the EC2 instance and deploy the app
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/app_backend
            git pull origin prod  
            npm install          
            npm run build         
            pm2 restart backend       
          EOF
